const ROLE_PERMISSIONS = Object.freeze({
  member: Object.freeze([
    'entry:read_shared',
    'tag:read',
    'comment:read',
    'comment:create',
    'comment:update',
    'comment:delete',
    'reaction:read',
    'reaction:use',
  ]),
  parent: Object.freeze([
    'entry:read_shared',
    'entry:read_all',
    'entry:create',
    'entry:update',
    'entry:delete',
    'album:upload',
    'care:read',
    'care:create',
    'care:update',
    'care:delete',
    'tag:read',
    'tag:assign',
    'comment:read',
    'comment:create',
    'comment:update',
    'comment:delete',
    'reaction:read',
    'reaction:use',
  ]),
  admin: Object.freeze([
    'entry:read_shared',
    'entry:read_all',
    'entry:create',
    'entry:update',
    'entry:delete',
    'album:upload',
    'care:read',
    'care:create',
    'care:update',
    'care:delete',
    'child:create',
    'child:update',
    'child:archive',
    'member:invite',
    'member:update_role',
    'member:disable',
    'album:manage',
    'tag:read',
    'tag:assign',
    'tag:manage',
    'comment:read',
    'comment:create',
    'comment:update',
    'comment:delete',
    'reaction:read',
    'reaction:use',
  ]),
})

export function permissionsFor(role) {
  return ROLE_PERMISSIONS[role] ?? []
}
